### PR TITLE
Implement fin-pmt

### LINKED ISSUE #3: [fin-pmt] Create element
Create element for PMT.

### PR DESCRIPTION
**Pull request by adamduren**
Closes #3

### CODE REVIEW

**Comment by zacharytamas** [comment]
What's the status on this?

**Comment by adamduren** [comment]
I need to write tests for it. Should have it done tomorrow.

**Comment by zacharytamas** [comment]
Sweet. I'll look forward to it.

**Comment by zacharytamas** [comment]
Did we ever get tests for this? :)

**Comment by adamduren** [comment]
I did try to use the bower version at first but fomulajs has a lot of dependencies and one of them has a lodash version conflict with a polymer lib we already have included. The bundled webkit version is just one self contained lib.

**Comment by zacharytamas** [comment]
:+1:

**Pull request merged**
